export const Constants = {
    FETCH_RECORDINGS_SUCCESS: "FETCH_RECORDINGS_SUCCESS",
    SAVE_RECORDING_SUCCESS: "SAVE_RECORDING_SUCCESS",
    DELETE_RECORDING_SUCCESS: "DELETE_RECORDING_SUCCESS",


    paths: {
        recordings: "/recordings"
    }
}